### ISSUE TITLE
ألن يتم وضع رابط تجريبي ؟

### ISSUE THREAD

**Issue by waseeld** [alifcommunity/next-website#1]
<div dir="rtl">

مرحبا بالعالم...
ألن يتم وضع رابط تجريبي ؟

قمت بترجبة الرابط الموضوع في الوصف :
https://alifcommunity.github.io/

لكنه يقوم بإعادة توجيهي الى الرابط :
http://aliflang.org/

لا أمتلك صلاحيات للعب في إعدادات هذا المستودع لذلك طرحت هذا هنا..

</div>

**Comment by assawalhy** [comment]
<div dir=rtl>

> قمت بترجبة الرابط الموضوع في الوصف :
> https://alifcommunity.github.io/
> 
> لكنه يقوم بإعادة توجيهي الى الرابط :
> http://aliflang.org/

أضفت ملف CNAME في البداية ثم حذفته وأظنك دخلت له قبل حذفه. والمتصفح يحتفظ بالبيانات ويجب أن تجبره على تحديث بيانات اسم النطاق.

1. افتح أدوات المطورين F12
2. اذهب لتبويب Network
3. فعِّل No Cache
4. حدث الموقع refresh

![image](https://user-images.githubusercontent.com/42011920/147207781-20a58e3c-d32f-485c-881f-081880034c32.png)

**Comment by waseeld** [comment]
<div dir="rtl">

شكرا لك , هذا الحل يعمل معي @MuhammadSawalhy 

</div>
