### ISSUE TITLE
تلوين كود ألف

### ISSUE THREAD

**Issue by assawalhy** [alifcommunity/next-website#2]
<div dir=rtl>

تستخدم Docusaurus مكتبة Prism في تلوين الكود ونريد أن نضع قواعدنا لتوين كود ألف.

وضعت مستعجلا بعض قواعد التلوين في [هذا الملف](https://github.com/alifcommunity/alifcommunity.github.io/blob/main/src/theme/prism-alif.js) لكنها لم تعمل كما ينبغي.

![image](https://user-images.githubusercontent.com/42011920/147208485-6eecc560-bb55-4a64-8a9a-149ae8d29e88.png)

</div>

**Comment by assawalhy** [comment]
@waseeld

**Comment by waseeld** [comment]
<div dir="rtl">
مرحبا, أشكر محاولتك تنبيهي هنا...
للأسف في جيثهوب لا يوجد نظام اشعار جيد هه.. :face_with_head_bandage: 

<br>
<br>
عموما لست جيدا في اختيار الألوان اقترح وضع الموضوع للنقاش في المجموعة لعل وعسى نجد من لديه ذوق جيد في ذلك...

</div>

**Comment by assawalhy** [comment]
<div dir="rtl">

> عموما لست جيدا في اختيار الألوان اقترح وضع الموضوع للنقاش في المجموعة لعل وعسى نجد من لديه ذوق جيد في ذلك...

الألوان تحدد من إعدادات ~~الكسل~~ الشكل theme في ملف docusaurus.config.js، ما اتحدث عنه هي قواعد التلوين نفسها. مثلا الكلمات الدلالية أو المفتاحية مثل"دالة"، "مجال"، "صنف"، "عدد".... وتلوين النص string والأعداد وغيرها من قواعد التلوين.

المكتبة المستخدمة هي prism وسأنظر في قواعد تلوين اللغات الأخرى إن شاء الله وأكمل قواعد ألف إن شاء الله عندما أجد وقتا 😅

**Comment by waseeld** [comment]
> الألوان تحدد من إعدادات الكسل theme في ملف docusaurus.config.js، ما اتحدث عنه هي قواعد التلوين نفسها. مثلا الكلمات الدلالية أو المفتاحية مثل"دالة"، "مجال"، "صنف"، "عدد".... وتلوين النص string والأعداد وغيرها من قواعد التلوين.
> 
> المكتبة المستخدمة هي prism وسأنظر في قواعد تلوين اللغات الأخرى إن شاء الله وأكمل قواعد ألف إن شاء الله عندما أجد وقتا sweat_smile

اهاا نعم وصلت الفكرة الآن...
يبدو الامر مثيرا سأقوم بالبحث ايضا عندما اجد وقتا لذلك..
شكرا لتوضيحك :+1:

**Comment by assawalhy** [comment]
https://github.com/alifcommunity/alifcommunity.github.io/commit/ecb5b870ef2815cb6799fb97b26cb10482b1f54a
