### ISSUE TITLE
اقتراح : فصل توثيق الاصدار الثالث عن الثاني

### ISSUE THREAD

**Issue by waseeld** [alifcommunity/next-website#3]
مارئيكم بالفصل بين توثيق الف 3 و 2 ...
من باب التنظيم + لا أريد كتابة عن ألف 2 قمت قبل قليل بالبدء فعليا بكتابة المقدمة لكن كنت اتحدث بشكل خاص عن الف 3

اقصد بفصل بينهما مثلا ان يحصل كل منها على subdomain مختلف مثل الفكرة المطبقة في vue ...

او انيحصلا على مسارات مختلفة قيلا .

الهدف :
 - جعل الامر اسهل على الوافدين الجدد
 - تسهيل الامر على المساهمين
 - تنظيم اكثر

**Comment by assawalhy** [comment]
<div dir=rtl>

تقدم docusaurus ميزة [تعديد الإصدارات](https://docusaurus.io/docs/versioning)...
</div>

```bash
yarn run docusaurus docs:version 2
```

<div dir=rtl>


الآن نحن لدينا الإصدار الثاني في `./versioned_docs/version-2` والإصدار الثالث في `./docs` وهو الإصدار المسمى Next

**Comment by waseeld** [comment]
> تقدم docusaurus ميزة [تعديد الإصدارات](https://docusaurus.io/docs/versioning)...
> 
> ```shell
> yarn run docusaurus docs:version 2
> ```
> 
> الآن نحن لدينا الإصدار الثاني في `./versioned_docs/version-2` والإصدار الثالث في `./docs` وهو الإصدار المسمى Next

رائع شكرا لك :+1:
